/**
* Automatically Generated by Reflow at 2022-02-01T01:02:12.337Z
* */

'use strict'

module.exports = {
    engine: "SequelizeEngine",
    dependency: "16_auto_migration_1642791083444",
    operations: (models, actions) => {
        return [
			new actions.ChangeColumn(
        		"Workspace",
        		"logoImageBucket",
        		new models.fields.CharField({"underscored":true,"primaryKey":false,"defaultValue":"reflow-crm","allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"logo_image_bucket","customAttributes":{},"attributeName":"logoImageBucket","maxLength":200}),
        		new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"logo_image_bucket","customAttributes":{},"attributeName":"logoImageBucket","maxLength":200})
    		),
			new actions.ChangeColumn(
        		"Workspace",
        		"logoImagePath",
        		new models.fields.CharField({"underscored":true,"primaryKey":false,"defaultValue":"company-logo","allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"logo_image_path","customAttributes":{},"attributeName":"logoImagePath","maxLength":250}),
        		new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"logo_image_path","customAttributes":{},"attributeName":"logoImagePath","maxLength":250})
    		),
        ]
    }
}