/**
* Automatically Generated by Reflow at 2022-02-12T23:54:54.709Z
* */

'use strict'

module.exports = {
    engine: "SequelizeEngine",
    dependency: "19_auto_migration_1643743406083",
    operations: (models, actions) => {
        return [
			new actions.ChangeColumn(
        		"Workspace",
        		"logoImageBucket",
        		new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"logo_image_bucket","customAttributes":{},"attributeName":"logoImageBucket","maxLength":200}),
        		new models.fields.CharField({"underscored":true,"primaryKey":false,"defaultValue":"reflow-crm","allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"logo_image_bucket","customAttributes":{},"attributeName":"logoImageBucket","maxLength":200})
    		),
        ]
    }
}