/**
* Automatically Generated by Reflow at 2022-02-12T23:54:54.710Z
* */

'use strict'

module.exports = {
    engine: "SequelizeEngine",
    dependency: "21_auto_migration_1644710094710",
    operations: (models, actions) => {
        return [
			new actions.CreateColumn(
        		"UserWorkspaces",
        		"profileImageUrl",
        		new models.fields.TextField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"profile_image_url","customAttributes":{},"attributeName":"profileImageUrl"})
    		),
			new actions.CreateColumn(
        		"UserWorkspaces",
        		"profileImagePath",
        		new models.fields.CharField({"underscored":true,"primaryKey":false,"defaultValue":"user-profile","allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"profile_image_path","customAttributes":{},"attributeName":"profileImagePath","maxLength":250})
    		),
			new actions.CreateColumn(
        		"UserWorkspaces",
        		"profileImageBucket",
        		new models.fields.CharField({"underscored":true,"primaryKey":false,"defaultValue":"reflow-crm","allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"profile_image_bucket","customAttributes":{},"attributeName":"profileImageBucket","maxLength":200})
    		),
			new actions.ChangeColumn(
        		"Workspace",
        		"logoImagePath",
        		new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"logo_image_path","customAttributes":{},"attributeName":"logoImagePath","maxLength":250}),
        		new models.fields.CharField({"underscored":true,"primaryKey":false,"defaultValue":"company-logo","allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"logo_image_path","customAttributes":{},"attributeName":"logoImagePath","maxLength":250})
    		),
        ]
    }
}