/**
* Automatically Generated by Reflow at 2021-12-24T22:07:33.369Z
* */

'use strict'

module.exports = {
    engine: "SequelizeEngine",
    dependency: "2_auto_migration_1640383653369",
    operations: (models, actions) => {
        return [
			new actions.CreateModel(
        		"UserWorkspaces",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					user:new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"user_id","customAttributes":{},"attributeName":"user","relatedTo":"User","fieldName":"userId","onDelete":"cascade","relatedName":null,"toField":null}),
					workspace:new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"workspace_id","customAttributes":{},"attributeName":"workspace","relatedTo":"Workspace","fieldName":"workspaceId","onDelete":"cascade","relatedName":null,"toField":null}),
					profileType:new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"profile_type_id","customAttributes":{},"attributeName":"profileType","relatedTo":"ProfileType","fieldName":"profileTypeId","onDelete":"cascade","relatedName":null,"toField":null}),
					dateJoined:new models.fields.DatetimeField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"date_joined","customAttributes":{},"attributeName":"dateJoined","autoNow":false,"autoNowAdd":true}),
					isActive:new models.fields.BooleanField({"underscored":true,"primaryKey":false,"defaultValue":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"is_active","customAttributes":{},"attributeName":"isActive"}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "user_workspaces",
					managed: true,
					ordering: [],
					indexes: [],
					customOptions: {},
				}
    		),
        ]
    }
}