/**
* Automatically Generated by Reflow at 2021-12-24T22:07:33.368Z
* */

'use strict'

module.exports = {
    engine: "SequelizeEngine",
    dependency: "",
    operations: (models, actions) => {
        return [
			new actions.CreateModel(
        		"LocationType",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					name:new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"name","customAttributes":{},"attributeName":"name","maxLength":200}),
					order:new models.fields.IntegerField({"underscored":true,"primaryKey":false,"defaultValue":1,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"order","customAttributes":{},"attributeName":"order"}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "location_type",
					managed: true,
					ordering: ["order"],
					indexes: [],
					customOptions: {},
				}
    		),
			new actions.CreateModel(
        		"AddressHelper",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					locationType:new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"location_type_id","customAttributes":{},"attributeName":"locationType","relatedTo":"LocationType","fieldName":"locationTypeId","onDelete":"cascade","relatedName":null,"toField":null}),
					countryCode:new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"country_code","customAttributes":{},"attributeName":"countryCode","maxLength":50}),
					countryName:new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"country_name","customAttributes":{},"attributeName":"countryName","maxLength":200}),
					state:new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"state","customAttributes":{},"attributeName":"state","maxLength":400}),
					stateCode:new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"state_code","customAttributes":{},"attributeName":"stateCode","maxLength":400}),
					city:new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"city","customAttributes":{},"attributeName":"city","maxLength":400}),
					order:new models.fields.BigIntegerField({"underscored":true,"primaryKey":false,"defaultValue":1,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"order","customAttributes":{},"attributeName":"order"}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "address_helper",
					managed: true,
					ordering: ["order"],
					indexes: [],
					customOptions: {},
				}
    		),
			new actions.CreateModel(
        		"ProfileType",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					name:new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"name","customAttributes":{},"attributeName":"name","maxLength":200}),
					canEdit:new models.fields.BooleanField({"underscored":true,"primaryKey":false,"defaultValue":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"can_edit","customAttributes":{},"attributeName":"canEdit"}),
					order:new models.fields.IntegerField({"underscored":true,"primaryKey":false,"defaultValue":1,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"order","customAttributes":{},"attributeName":"order"}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "profile_type",
					managed: true,
					ordering: ["order"],
					indexes: [],
					customOptions: {},
				}
    		),
			new actions.CreateModel(
        		"User",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					dateJoined:new models.fields.DatetimeField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"date_joined","customAttributes":{},"attributeName":"dateJoined","autoNow":false,"autoNowAdd":true}),
					isSuperuser:new models.fields.BooleanField({"underscored":true,"primaryKey":false,"defaultValue":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"is_superuser","customAttributes":{},"attributeName":"isSuperuser"}),
					firstName:new models.fields.TextField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"first_name","customAttributes":{},"attributeName":"firstName"}),
					lastName:new models.fields.TextField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"last_name","customAttributes":{},"attributeName":"lastName"}),
					email:new models.fields.TextField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"email","customAttributes":{},"attributeName":"email"}),
					isStaff:new models.fields.BooleanField({"underscored":true,"primaryKey":false,"defaultValue":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"is_staff","customAttributes":{},"attributeName":"isStaff"}),
					tempPassword:new models.fields.CharField({"underscored":true,"primaryKey":false,"defaultValue":null,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"temp_password","customAttributes":{},"attributeName":"tempPassword","maxLength":250}),
					lastLogin:new models.fields.DatetimeField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"last_login","customAttributes":{},"attributeName":"lastLogin","autoNow":false,"autoNowAdd":false}),
					username:new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":true,"dbIndex":false,"databaseName":"username","customAttributes":{},"attributeName":"username","maxLength":150}),
					password:new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"password","customAttributes":{},"attributeName":"password","maxLength":150}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "user",
					managed: true,
					ordering: [],
					indexes: [],
					customOptions: {},
				}
    		),
			new actions.CreateModel(
        		"Workspace",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					updatedAt:new models.fields.DatetimeField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"updated_at","customAttributes":{},"attributeName":"updatedAt","autoNow":true,"autoNowAdd":false}),
					createdAt:new models.fields.DatetimeField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"created_at","customAttributes":{},"attributeName":"createdAt","autoNow":false,"autoNowAdd":true}),
					name:new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":true,"databaseName":"name","customAttributes":{},"attributeName":"name","maxLength":400}),
					endpoint:new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":true,"dbIndex":true,"databaseName":"endpoint","customAttributes":{},"attributeName":"endpoint","maxLength":280}),
					isActive:new models.fields.BooleanField({"underscored":true,"primaryKey":false,"defaultValue":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":true,"databaseName":"is_active","customAttributes":{},"attributeName":"isActive"}),
					sharedBy:new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"shared_by_id","customAttributes":{},"attributeName":"sharedBy","relatedTo":"Company","fieldName":"sharedById","onDelete":"set_null","relatedName":"sharedFromCompanies","toField":null}),
					partner:new models.fields.CharField({"underscored":true,"primaryKey":false,"defaultValue":null,"allowBlank":false,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"partner","customAttributes":{},"attributeName":"partner","maxLength":500}),
					logoImageBucket:new models.fields.CharField({"underscored":true,"primaryKey":false,"defaultValue":"reflow-crm","allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"logo_image_bucket","customAttributes":{},"attributeName":"logoImageBucket","maxLength":200}),
					logoImagePath:new models.fields.CharField({"underscored":true,"primaryKey":false,"defaultValue":"company-logo","allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"logo_image_path","customAttributes":{},"attributeName":"logoImagePath","maxLength":250}),
					logoImageUrl:new models.fields.CharField({"underscored":true,"primaryKey":false,"defaultValue":null,"allowBlank":false,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"logo_image_url","customAttributes":{},"attributeName":"logoImageUrl","maxLength":1000}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "workspace",
					managed: true,
					ordering: [],
					indexes: [],
					customOptions: {},
				}
    		),
        ]
    }
}