/**
* Automatically Generated by Reflow at 2022-01-06T16:49:21.298Z
* */

'use strict'

module.exports = {
    engine: "SequelizeEngine",
    dependency: "6_auto_migration_1640825619398",
    operations: (models, actions) => {
        return [
			new actions.ChangeColumn(
        		"Workspace",
        		"uuid",
        		new models.fields.UUIDField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":true,"unique":false,"dbIndex":true,"databaseName":"uuid","customAttributes":{},"attributeName":"uuid","maxLength":32,"autoGenerate":false}),
        		new models.fields.UUIDField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":true,"unique":false,"dbIndex":true,"databaseName":"uuid","customAttributes":{},"attributeName":"uuid","maxLength":36,"autoGenerate":false})
    		),
        ]
    }
}