module.exports = {
    OBJECT_TYPE: 'object',
    INTEGER_TYPE: 'int',
    FLOAT_TYPE: 'float',
    NONE_TYPE: 'none',
    BOOLEAN_TYPE: 'boolean',
    FUNCTION_TYPE: 'function',
    STRING_TYPE: 'string',
    ERROR_TYPE: 'error',
    LIST_TYPE: 'list',
    DICT_TYPE: 'dict',
    MODULE_TYPE: 'module',
    STRUCT_TYPE: 'struct',
    DATETIME_TYPE: 'datetime',
}