module.exports = {
    client: {
        selectCreateLabel: 'Criar',
        sidebarHelloName: 'Olá, ',
        sidebarQuickSearchButtonLabel: 'Pesquisa Rápida',
        sidebarHistoryButtonLabel: 'Histórico',
        sidebarSettingsButtonLabel: 'Configurações',
        sidebarWorkspacesTitle: 'ESPAÇOS DE TRABALHO',
        workspaceEditColor: 'Cores',
        workspaceNewAreaName: 'Workspace sem nome',
        workspaceRemoveButtonLabel: 'Remover workspace',
        workspaceAddNewAppButtonLabel: 'Novo App',
        workspaceNoAppSelected: 'Nenhum app selecionado',
        workspaceNoWorkspaceSelected: 'Nenhum workspace selecionado',
        workspaceNotUniqueErrorMessage: 'Nome do workspace deve ser único',
        formularyToolbarShareButtonLabel: 'Compartilhar',
        formularyFieldEditIsRequiredLabel: 'Obrigatório',
        formularyFieldEditLabelIsHiddenLabel: 'Ocultar titulo',
        formularyFieldEditFieldIsHiddenLabel: 'Ocultar campo',
        formularyFieldEditFieldIsUniqueLabel: 'Valor é único',
        formularyFieldEditLabelAndFieldIsHiddenMessage: 'O campo "{}" está oculto',
        formularyFieldEditRenameLabel: 'Renomear',
        formularyFieldEditDuplicateLabel: 'Duplicar',
        formularyFieldEditEditLabel: 'Editar',
        formularyFieldEditDeleteLabel: 'Excluir',
        formularyFieldNumberDefaultDecimalCharacter: ',',
        formularyFieldNumberDefaultThousandSeparatorCharacter: '.',
        formularyFieldNumberDropdownMenuNumberFormatOptionLabel: 'Selecione a formatação',
        formularyFieldOptionCustomHelperLabelIfIsAdmin: 'Selecione uma opção ou escreva para criar uma nova',
        formularyFieldOptionCustomHelperLabelIfIsNotAdmin: 'Selecione uma opção',
        formularyFieldOptionCreateOptionLabel: 'Criar',
        formularyFieldOptionEditOptionMenuRenameButtonLabel: 'Renomear',
        formularyFieldOptionEditOptionMenuDeleteButtonLabel: 'Excluir',
        formularyFieldOptionEditOptionMenuColorLabel: 'Cores',
        formularyFieldOptionDropdownMenuIsDropdownLabel: 'Menu de seleção',
        formularyFieldAttachmentPlaceholder: 'Clique ou arraste os arquivos aqui',
        formularyFieldAttachmentDragAndDropFileMessage: 'SOLTE OS ARQUIVOS AQUI',
        formularyFieldAttachmentDetailCloseButtonDescriptionLabel: 'Fechar',
        formularyFieldAttachmentDetailRemoveButtonDescriptionLabel: 'Excluir',
        formularyFieldAttachmentDetailDownloadButtonDescriptionLabel: 'Download',
        formularyFieldIdDescriptionLabel: 'Esse valor é gerado dinâmicamente',
        formularyFieldFormulaDescriptionLabel: 'Esse valor é calculado dinamicamente',
        numberFormatTypeNumberLabel: 'Dinâmico',
        numberFormatTypeIntegerLabel: 'Inteiro',
        numberFormatTypeCurrencyLabel: 'Monetário',
        numberFormatTypePercentageLabel: 'Porcentagem',
        datePickerMonthOfTheYearJanuaryLabel: 'Janeiro',
        datePickerMonthOfTheYearFebruaryLabel: 'Fevereiro',
        datePickerMonthOfTheYearMarchLabel: 'Março',
        datePickerMonthOfTheYearAprilLabel: 'Abril',
        datePickerMonthOfTheYearMayLabel: 'Maio',
        datePickerMonthOfTheYearJuneLabel: 'Junho',
        datePickerMonthOfTheYearJulyLabel: 'Julho',
        datePickerMonthOfTheYearAugustLabel: 'Agosto',
        datePickerMonthOfTheYearSeptemberLabel: 'Setembro',
        datePickerMonthOfTheYearOctoberLabel: 'Outubro',
        datePickerMonthOfTheYearNovemberLabel: 'Novembro',
        datePickerMonthOfTheYearDecemberLabel: 'Dezembro',
        datePickerDayOfTheWeekSundayLabel: 'Domingo',
        datePickerDayOfTheWeekMondayLabel: 'Segunda',
        datePickerDayOfTheWeekTuesdayLabel: 'Terça',
        datePickerDayOfTheWeekWednesdayLabel: 'Quarta',
        datePickerDayOfTheWeekThursdayLabel: 'Quinta',
        datePickerDayOfTheWeekFridayLabel: 'Sexta',
        datePickerDayOfTheWeekSaturdayLabel: 'Sábado',
        datePickerDefaultFormat: 'DD/MM/YYYY'
    },
    server: {
        loginInvalidPassOrUserError: 'Usuário ou senha inválidos',
        areaNameExistsError: 'O nome da área deve ser único para todo o workspace',
        jwtTokenNotProvidedError: 'Token JWT não fornecido na requisição',
        jwtTokenNotValidAnymoreError: 'JWT token fornecido expirou e não é mais válido',
        refreshTokenIsNotARefreshTokenOrDoesNotExistError: 'Refresh token não é um refresh token ou não existe',
        refreshTokenIsNotValid: 'Refresh token não é válido',
        draftFileNotUploadedError: 'Por alguma razão o arquivo não foi carregado ou os dados recebidos não são válidos (o workspace não foi encontrado), então tente fazer o upload novamente'
    }
}