module.exports = {
    client: {
        selectCreateLabel: 'Criar',
        sidebarHelloName: 'Olá, ',
        sidebarQuickSearchButtonLabel: 'Pesquisa Rápida',
        sidebarHistoryButtonLabel: 'Histórico',
        sidebarSettingsButtonLabel: 'Configurações',
        sidebarWorkspacesTitle: 'ESPAÇOS DE TRABALHO',
        sidebarCreateNewWorkspaceButtonLabel: '+ Criar novo workspace',
        workspaceEditColor: 'Cores',
        workspaceNewAreaName: 'Workspace sem nome',
        workspaceRemoveButtonLabel: 'Remover workspace',
        workspaceAddNewAppButtonLabel: 'Novo App',
        workspaceNoAppSelected: 'Nenhum app selecionado',
        workspaceNoWorkspaceSelected: 'Nenhum workspace selecionado',
        workspaceNotUniqueErrorMessage: 'Nome do workspace deve ser único',
        fieldTypeHeadingIconLabel: 'C',
        formularyToolbarShareButtonLabel: 'Compartilhar',
        formularyAddFieldTooltipButtonLabel: 'Adicionar novo campo',
        formularyNewFieldLabel: 'Novo',
        formularyCopyFieldLabel: 'cópia',
        formularyFieldEditIsRequiredLabel: 'Obrigatório',
        formularyFieldEditLabelIsHiddenLabel: 'Ocultar titulo',
        formularyFieldEditFieldIsHiddenLabel: 'Ocultar campo',
        formularyFieldEditFieldIsUniqueLabel: 'Valor é único',
        formularyFieldEditLabelAndFieldIsHiddenMessage: 'O campo "{}" está oculto',
        formularyFieldEditRenameLabel: 'Renomear',
        formularyFieldEditDuplicateLabel: 'Duplicar',
        formularyFieldEditEditLabel: 'Editar',
        formularyFieldEditDeleteLabel: 'Excluir',
        formularyFieldNumberDefaultDecimalCharacter: ',',
        formularyFieldNumberDefaultThousandSeparatorCharacter: '.',
        formularyFieldNumberDropdownMenuNumberFormatOptionLabel: 'Selecione a formatação',
        formularyFieldOptionCustomHelperLabelIfIsAdmin: 'Selecione uma opção ou escreva para criar uma nova',
        formularyFieldOptionCustomHelperLabelIfIsNotAdmin: 'Selecione uma opção',
        formularyFieldOptionCreateOptionLabel: 'Criar',
        formularyFieldOptionEditOptionMenuRenameButtonLabel: 'Renomear',
        formularyFieldOptionEditOptionMenuDeleteButtonLabel: 'Excluir',
        formularyFieldOptionEditOptionMenuColorLabel: 'Cores',
        formularyFieldOptionDropdownMenuIsDropdownLabel: 'Menu de seleção',
        formularyFieldAttachmentPlaceholder: 'Clique ou arraste os arquivos aqui',
        formularyFieldAttachmentDragAndDropFileMessage: 'SOLTE OS ARQUIVOS AQUI',
        formularyFieldAttachmentDetailCloseButtonDescriptionLabel: 'Fechar',
        formularyFieldAttachmentDetailRemoveButtonDescriptionLabel: 'Excluir',
        formularyFieldAttachmentDetailDownloadButtonDescriptionLabel: 'Download',
        formularyFieldDateDropdownMenuAutomaticToCreate: 'Automático ao criar',
        formularyFieldDateDropdownMenuAutomaticToUpdate: 'Automático ao atualizar',
        formularyFieldIdDescriptionLabel: 'Esse valor é gerado dinâmicamente',
        formularyFieldFormulaDescriptionLabel: 'Esse valor é calculado automaticamente',
        formularyFieldFormulaEmptyValueDescriptionLabel: 'Clique aqui para editar uma fórmula',
        formularyFieldFormulaDoneEditingFormula: 'Finalizar edição',
        formularyFieldFormulaDropdownMenuToEditFormulaLabel: 'Editar formula',
        formularyFieldFormulaDropdownMenuToFinishEditOnFormulaLabel: 'Concluir edição',
        formularyFieldFormulaVariableDescription: 'Esta é uma váriavel. Uma variável refere-se a um dos campos do seu formulário. O valor de uma variável é definida pelo valor no campo.',
        formularyFieldConnectionFormularySelectLabel: 'Selecione a qual app este campo se conecta',
        formularyFieldConnectionFieldSelectLabel: 'Selecione o campo para usar como opção',
        flowIfSnippetCondition: 'condição',
        flowIfSnippetWhenTrue: 'quando verdadeiro',
        flowIfSnippetWhenFalse: 'quando falso',
        flowIfSnippetFirstCondition: '1º condição',
        flowIfSnippetWhenFirstCondition: 'quando 1º condição',
        flowIfSnippetSecondCondition: '2º condição',
        flowIfSnippetWhenSecondCondition: 'quando 2º condição',
        flowIfSnippetWhenNoCondition: 'quando nenhuma condição',
        flowFunctionSnippetName: 'nome',
        flowFunctionSnippetParameters: 'parâmetros',
        flowFunctionSnippetDo: 'fazer',
        flowFunctionLambdaName: 'lambda',
        flowFunctionAnonymousName: 'anônima',
        flowDescriptionDescriptionLabel: 'Descrição',
        flowDescriptionExampleLabel: 'Exemplos',
        flowDescriptionParametersLabel: 'Argumentos',
        fieldTypeNumberLabel: 'Número',
        fieldTypeTextLabel: 'Texto',
        fieldTypeDateLabel: 'Data',
        fieldTypeOptionLabel: 'Opção',
        fieldTypeConnectionLabel: 'Conexão',
        fieldTypeAttachmentLabel: 'Anexo',
        fieldTypeLongTextLabel: 'Texto Longo',
        fieldTypeEmailLabel: 'E-mail',
        fieldTypeIdLabel: 'id',
        fieldTypeUserLabel: 'Usuários',
        fieldTypeFormulaLabel: 'Formula',
        fieldTypeTagsLabel: 'Tags',
        fieldTypeCheckboxLabel: 'Verdadeiro/Falso',
        fieldTypeMultiFieldLabel: 'Múltiplos Campos',
        fieldTypeHeading1Label: 'Cabeçalho 1',
        fieldTypeHeading2Label: 'Cabeçalho 2',
        fieldTypeHeading3Label: 'Cabeçalho 3',
        numberFormatTypeNumberLabel: 'Dinâmico',
        numberFormatTypeIntegerLabel: 'Inteiro',
        numberFormatTypeCurrencyLabel: 'Monetário',
        numberFormatTypePercentageLabel: 'Porcentagem',
        datePickerMonthOfTheYearJanuaryLabel: 'Janeiro',
        datePickerMonthOfTheYearFebruaryLabel: 'Fevereiro',
        datePickerMonthOfTheYearMarchLabel: 'Março',
        datePickerMonthOfTheYearAprilLabel: 'Abril',
        datePickerMonthOfTheYearMayLabel: 'Maio',
        datePickerMonthOfTheYearJuneLabel: 'Junho',
        datePickerMonthOfTheYearJulyLabel: 'Julho',
        datePickerMonthOfTheYearAugustLabel: 'Agosto',
        datePickerMonthOfTheYearSeptemberLabel: 'Setembro',
        datePickerMonthOfTheYearOctoberLabel: 'Outubro',
        datePickerMonthOfTheYearNovemberLabel: 'Novembro',
        datePickerMonthOfTheYearDecemberLabel: 'Dezembro',
        datePickerDayOfTheWeekSundayLabel: 'Domingo',
        datePickerDayOfTheWeekMondayLabel: 'Segunda',
        datePickerDayOfTheWeekTuesdayLabel: 'Terça',
        datePickerDayOfTheWeekWednesdayLabel: 'Quarta',
        datePickerDayOfTheWeekThursdayLabel: 'Quinta',
        datePickerDayOfTheWeekFridayLabel: 'Sexta',
        datePickerDayOfTheWeekSaturdayLabel: 'Sábado',
        datePickerDefaultFormat: 'DD/MM/YYYY'
    },
    server: {
        loginInvalidPassOrUserError: 'Usuário ou senha inválidos',
        areaNameExistsError: 'O nome da área deve ser único para todo o workspace',
        jwtTokenNotProvidedError: 'Token JWT não fornecido na requisição',
        jwtTokenNotValidAnymoreError: 'JWT token fornecido expirou e não é mais válido',
        refreshTokenIsNotARefreshTokenOrDoesNotExistError: 'Refresh token não é um refresh token ou não existe',
        refreshTokenIsNotValid: 'Refresh token não é válido',
        draftFileNotUploadedError: 'Por alguma razão o arquivo não foi carregado ou os dados recebidos não são válidos (o workspace não foi encontrado), então tente fazer o upload novamente'
    },
    shared: {
        flowIncludesKeyword: 'em',
        flowConjunctionKeyword: 'e',
        flowDisjunctionKeyword: 'ou',
        flowInversionKeyword: 'não',
        flowEqualityKeyword: 'é',
        flowInequalityKeyword: 'não é',
        flowDoKeyword: 'faça',
        flowEndKeyword: 'fim',
        flowNullKeyword: 'Vazio',
        flowTrueKeyword: 'Verdadeiro',
        flowFalseKeyword: 'Falso',
        flowIfKeyword: 'se',
        flowElseKeyword: 'senão',
        flowFunctionKeyword: 'função',
        flowReturnKeyword: 'retornar',
        flowRaiseKeyword: 'lançar',
        flowTryKeyword: 'tentar',
        flowCatchKeyword: 'caso contrário',
        flowModuleKeyword: 'módulo',
        flowDecimalPointSeparator: ',',
        flowPositionalArgumentSeparator: ';',
        flowTimezone: 'UTC',
        flowDateCharacter: 'D',
        flowDateFormat: 'DD/MM/YYYY',
        flowHourFormat: 'hh:mm:ss.SSS',
        flowDocumentationKeyword: '@doc',
        flowTailCallOptimizedMessage: 'Chamada recursiva otimizada',
        flowAttributesLabel: 'atributos',
        flowDocumentationDocumentationHeaderLabel: 'DOCUMENTAÇÃO',
        flowDocumentationExamplesHeaderLabel: 'EXEMPLOS',
        flowHTTPModuleName: 'HTTP',
        flowHTTPModuleDescription: 'Para fazer chamadas de API e ser capaz de conectar com outros serviços e sistemas legados',
        flowHTTPGetMethodName: 'get',
        flowHTTPGetMethodDescription: 'Isso irá pegar os dados de uma URL, geralmente uma api, e irá retorná-los em formato JSON',
        flowHTTPGetMethodExample: "resposta = HTTP.get('https://pokeapi.co/api/v2/pokemon/pikachu')\ndados_do_pikachu = resposta.json\ndados_do_pikachu['types'][0]['type']['name']" + 
                                  "\n\n# Com isso nós puxamos o dado do pokemon pikachu, recebemos a resposta\n# em formato json e navegamos pela estrutura dos dados até \n" + 
                                  "# pegarmos o que desejamos, que é o tipo do pokemon.\n" +
                                  "# O processo é o mesmo para conectar aplicações entre si.",
        flowHTTPUrlParameterName: 'endereço',
        flowHTTPUrlParameterDescription: 'O endereço para puxar/enviar/deletar ou atualizar um recurso de um serviço terceiro. Será sempre uma URL.',
        flowHTTPHeadersParameterName: 'cabeçalhos',
        flowHTTPHeadersParameterDescription: 'Um dicionário, com ele você poderá definir os `Cabeçalhos` em suas requisições. Essa é uma feature avançada.\nReferência: https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Headers',
        flowHTTPBasicAuthParameterName: 'autenticação_básica',
        flowHTTPBasicAuthParameterDescription: 'Em alguns momentos você irá precisar se autenticar ao realizar uma chamada de API. Um dos jeitos mais comuns de se autenticar em '+
                                               'uma API é com autenticação básica. Um exemplo é a API do Twilio que usa esse modelo de autenticação: https://www.twilio.com/docs/usage/api#authenticate-with-http',
        flowHTTPParametersParameterName: 'parâmetros',
        flowHTTPParametersParameterDescription: 'Os parâmetros da requisição. Geralmente são variáveis que você coloca no endereço da requisição. Por exemplo:\n' + 
                                                'https://www.google.com/search?q=pokemon&sxsrf=APq-WBuaJxe-i1gtqIZBFJ7Y2GV0Hv7OAw%3A1645462624540&ei=YMQTYvTSIIHC5OUPvsm1kAI&ved=0ahUKEwj0guj5oZH2AhUBIbkGHb5kDSIQ4dUDCA4&uact=5&oq=pokemon&gs_lcp=Cgdnd3Mtd2l6EAMyCwguEIAEELEDENQCMggILhCABBCxAzILCAAQgAQQsQMQgwEyBQguEIAEMggILhCABBCxAzIICC4QgAQQsQMyBQgAEIAEMggILhCABBCxAzIICAAQgAQQsQMyBQguEIAEOgcIIxCwAxAnOgcIABBHELADOgQIIxAnOgsILhCABBCxAxCDAToLCC4QsQMQgwEQ1AI6CAgAELEDEIMBOgQIABBDOg4ILhCABBCxAxDHARCjAjoOCC4QgAQQsQMQgwEQ1AJKBAhBGABKBAhGGABQogxYmxhgwhpoA3ABeACAAXyIAZsGkgEDMC43mAEAoAEByAEJwAEB&sclient=gws-wiz \n\n' +
                                                'Essa url pesquisa pelo termo pokemon no google. https://www.google.com/search é a url base. A partir do caractere `?` o restante são parâmetros separados por `&`. `q=` é um parametro, `pokemon` é o valor. ' +
                                                '`sxsrf=` é outro parâmetro e `APq-WBuaJxe-i1gtqIZBFJ7Y2GV0Hv7OAw%3A1645462624540` é o valor. Você consegue encontrar os outros parâmetros nessa url? Dica, são `ei=`, `ved=`, `uact=`, `oq=`, `gs_lcp=` e `sclient=`.',
        flowHTTPDataParameterName: 'dados',
        flowHTTPDataParameterDescription: 'Os dados que você quer enviar para o serviço terceiro. Esses dados serão form-encoded. Geralmente, você vai querer usar o parâmetro dados_json ao invés desse.',
        flowHTTPJsonDataParameterName: 'dados_json',
        flowHTTPJsonDataParameterDescription: 'Os dados que você quer enviar para o serviço terceiro. Diferentemente de `dados`, esses dados são enviados em formato json. O formato json atualmente é amplamente aceito e utilizado ' +
                                              'pela maioria dos serviços e APIs',
        flowHTTPPostMethodName: 'post',
        flowHTTPPostMethodDescription: 'Isso irá enviar dados para uma URL, geralmente uma api, e irá retorná-los em formato JSON caso a API retorne algum dado',
        flowHTTPPutMethodName: 'put',
        flowHTTPPutMethodDescription: '',
        flowHTTPDeleteMethodName: 'delete',
        flowHTTPDeleteMethodDescription: '',
        flowHTTPRequestMethodName: 'request',
        flowHTTPRequestMethodDescription: '',
    }
}