/**
* Automatically Generated by Palmares at 2022-04-11T21:46:37.127Z
* */

'use strict'

module.exports = {
    engine: "SequelizeEngine",
    dependency: "33_auto_migration_1649506322135",
    operations: (models, actions) => {
        return [
			new actions.CreateModel(
        		"AppType",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					name:new models.fields.TextField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"name","customAttributes":{},"attributeName":"name"}),
					order:new models.fields.IntegerField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"order","customAttributes":{},"attributeName":"order"}),
					isDefault:new models.fields.BooleanField({"underscored":true,"primaryKey":false,"defaultValue":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"is_default","customAttributes":{},"attributeName":"isDefault"}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "app_type",
					managed: true,
					ordering: ["order"],
					indexes: [],
					customOptions: {},
				}
    		),
			new actions.CreateColumn(
        		"App",
        		"appType",
        		new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"defaultValue":null,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"app_type_id","customAttributes":{},"attributeName":"appType","relatedTo":"AppType","fieldName":"appTypeId","onDelete":"cascade","relatedName":null,"toField":null})
    		),
        ]
    }
}