/**
* Automatically Generated by Reflow at 2021-12-30T00:53:39.398Z
* */

'use strict'

module.exports = {
    engine: "SequelizeEngine",
    dependency: "5_auto_migration_1640640453345",
    operations: (models, actions) => {
        return [
			new actions.ChangeColumn(
        		"Area",
        		"description",
        		new models.fields.TextField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"description","customAttributes":{},"attributeName":"description"}),
        		new models.fields.TextField({"underscored":true,"primaryKey":false,"defaultValue":null,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"description","customAttributes":{},"attributeName":"description"})
    		),
			new actions.RenameColumn(
        		"Area",
        		"subAreaOf",
        		"subArea",
        		new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false, "allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"sub_area_of_id","customAttributes":{},"attributeName":"subAreaOf","relatedTo":"Area","fieldName":"subAreaOfId","onDelete":"cascade","relatedName":"subAreas","toField":null})
    		),
			new actions.CreateColumn(
        		"Area",
        		"color",
        		new models.fields.TextField({"underscored":true,"primaryKey":false,"defaultValue":null,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"color","customAttributes":{},"attributeName":"color"})
    		),
			new actions.ChangeColumn(
        		"Area",
        		"subAreaOf",
        		new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"sub_area_id","customAttributes":{},"attributeName":"subArea","relatedTo":"Area","fieldName":"subAreaId","onDelete":"cascade","relatedName":"subAreas","toField":null}),
        		new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"sub_area_of_id","customAttributes":{},"attributeName":"subAreaOf","relatedTo":"Area","fieldName":"subAreaOfId","onDelete":"cascade","relatedName":"subAreas","toField":null})
    		),
        ]
    }
}