/**
* Automatically Generated by Reflow at 2022-01-06T16:49:21.298Z
* */

'use strict'

module.exports = {
    engine: "SequelizeEngine",
    dependency: "7_auto_migration_1641487761298",
    operations: (models, actions) => {
        return [
			new actions.ChangeColumn(
        		"Area",
        		"subAreaOf",
        		new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"sub_area_of_id","customAttributes":{},"attributeName":"subAreaOf","relatedTo":"Area","fieldName":"subAreaOfId","onDelete":"cascade","relatedName":"subAreas","toField":null}),
        		new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"sub_area_of_id","customAttributes":{},"attributeName":"subAreaOf","relatedTo":"Area","fieldName":"subAreaOfId","onDelete":"set_null","relatedName":"subAreas","toField":null})
    		),
			new actions.ChangeColumn(
        		"Area",
        		"uuid",
        		new models.fields.UUIDField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"uuid","customAttributes":{},"attributeName":"uuid","maxLength":32,"autoGenerate":false}),
        		new models.fields.UUIDField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"uuid","customAttributes":{},"attributeName":"uuid","maxLength":36,"autoGenerate":false})
    		),
			new actions.ChangeColumn(
        		"AvailableApp",
        		"uuid",
        		new models.fields.UUIDField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"uuid","customAttributes":{},"attributeName":"uuid","maxLength":32,"autoGenerate":false}),
        		new models.fields.UUIDField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"uuid","customAttributes":{},"attributeName":"uuid","maxLength":36,"autoGenerate":false})
    		),
			new actions.ChangeColumn(
        		"App",
        		"uuid",
        		new models.fields.UUIDField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"uuid","customAttributes":{},"attributeName":"uuid","maxLength":32,"autoGenerate":false}),
        		new models.fields.UUIDField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"uuid","customAttributes":{},"attributeName":"uuid","maxLength":36,"autoGenerate":false})
    		),
        ]
    }
}