/**
* Automatically Generated by Reflow at 2021-12-24T22:07:33.369Z
* */

'use strict'

module.exports = {
    engine: "SequelizeEngine",
    dependency: "1_auto_migration_1640383653369",
    operations: (models, actions) => {
        return [
			new actions.CreateModel(
        		"Area",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					createdAt:new models.fields.DatetimeField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"created_at","customAttributes":{},"attributeName":"createdAt","autoNow":false,"autoNowAdd":true}),
					updatedAt:new models.fields.DatetimeField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"updated_at","customAttributes":{},"attributeName":"updatedAt","autoNow":true,"autoNowAdd":false}),
					uuid:new models.fields.UUIDField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"uuid","customAttributes":{},"attributeName":"uuid","maxLength":32,"autoGenerate":false}),
					name:new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"name","customAttributes":{},"attributeName":"name","maxLength":255}),
					labelName:new models.fields.TextField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"label_name","customAttributes":{},"attributeName":"labelName"}),
					description:new models.fields.TextField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"description","customAttributes":{},"attributeName":"description"}),
					order:new models.fields.IntegerField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"order","customAttributes":{},"attributeName":"order"}),
					workspace:new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"workspace_id","customAttributes":{},"attributeName":"workspace","relatedTo":"Workspace","fieldName":"workspaceId","onDelete":"cascade","relatedName":null,"toField":null}),
					subArea:new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"sub_area_id","customAttributes":{},"attributeName":"subArea","relatedTo":"Area","fieldName":"subAreaId","onDelete":"cascade","relatedName":"subAreas","toField":null}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "area",
					managed: true,
					ordering: ["order"],
					indexes: [],
					customOptions: {},
				}
    		),
        ]
    }
}