/**
* Automatically Generated by Reflow at 2021-12-24T22:07:33.369Z
* */

'use strict'

module.exports = {
    engine: "SequelizeEngine",
    dependency: "3_auto_migration_1640383653369",
    operations: (models, actions) => {
        return [
			new actions.CreateModel(
        		"MetadataType",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					name:new models.fields.TextField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"name","customAttributes":{},"attributeName":"name"}),
					order:new models.fields.IntegerField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"order","customAttributes":{},"attributeName":"order"}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "metadata_type",
					managed: true,
					ordering: ["order"],
					indexes: [],
					customOptions: {},
				}
    		),
			new actions.CreateModel(
        		"AvailableApp",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					createdAt:new models.fields.DatetimeField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"created_at","customAttributes":{},"attributeName":"createdAt","autoNow":false,"autoNowAdd":true}),
					updatedAt:new models.fields.DatetimeField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"updated_at","customAttributes":{},"attributeName":"updatedAt","autoNow":true,"autoNowAdd":false}),
					uuid:new models.fields.UUIDField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"uuid","customAttributes":{},"attributeName":"uuid","maxLength":32,"autoGenerate":false}),
					name:new models.fields.TextField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"name","customAttributes":{},"attributeName":"name"}),
					description:new models.fields.TextField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"description","customAttributes":{},"attributeName":"description"}),
					isBuiltin:new models.fields.BooleanField({"underscored":true,"primaryKey":false,"defaultValue":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"is_builtin","customAttributes":{},"attributeName":"isBuiltin"}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "available_app",
					managed: true,
					ordering: [],
					indexes: [],
					customOptions: {},
				}
    		),
			new actions.CreateModel(
        		"App",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					createdAt:new models.fields.DatetimeField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"created_at","customAttributes":{},"attributeName":"createdAt","autoNow":false,"autoNowAdd":true}),
					updatedAt:new models.fields.DatetimeField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"updated_at","customAttributes":{},"attributeName":"updatedAt","autoNow":true,"autoNowAdd":false}),
					uuid:new models.fields.UUIDField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"uuid","customAttributes":{},"attributeName":"uuid","maxLength":32,"autoGenerate":false}),
					name:new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"name","customAttributes":{},"attributeName":"name","maxLength":255}),
					labelName:new models.fields.TextField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"label_name","customAttributes":{},"attributeName":"labelName"}),
					description:new models.fields.TextField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"description","customAttributes":{},"attributeName":"description"}),
					area:new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"area_id","customAttributes":{},"attributeName":"area","relatedTo":"Area","fieldName":"areaId","onDelete":"cascade","relatedName":null,"toField":null}),
					selectedApp:new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"selected_app_id","customAttributes":{},"attributeName":"selectedApp","relatedTo":"AvailableApp","fieldName":"selectedAppId","onDelete":"cascade","relatedName":null,"toField":null}),
					order:new models.fields.IntegerField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"order","customAttributes":{},"attributeName":"order"}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "app",
					managed: true,
					ordering: ["order"],
					indexes: [],
					customOptions: {},
				}
    		),
			new actions.CreateModel(
        		"AppRelatedTo",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					app:new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"app_id","customAttributes":{},"attributeName":"app","relatedTo":"App","fieldName":"appId","onDelete":"cascade","relatedName":null,"toField":null}),
					relatedTo:new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"related_to_id","customAttributes":{},"attributeName":"relatedTo","relatedTo":"App","fieldName":"relatedToId","onDelete":"cascade","relatedName":null,"toField":null}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "app_related_to",
					managed: true,
					ordering: [],
					indexes: [],
					customOptions: {},
				}
    		),
			new actions.CreateModel(
        		"RequiredMetadataForApp",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					metadataType:new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"metadata_type_id","customAttributes":{},"attributeName":"metadataType","relatedTo":"MetadataType","fieldName":"metadataTypeId","onDelete":"cascade","relatedName":null,"toField":null}),
					name:new models.fields.TextField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"name","customAttributes":{},"attributeName":"name"}),
					isRequired:new models.fields.BooleanField({"underscored":true,"primaryKey":false,"defaultValue":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"is_required","customAttributes":{},"attributeName":"isRequired"}),
					defaultValue:new models.fields.TextField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"default_value","customAttributes":{},"attributeName":"defaultValue"}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "required_metadata_for_app",
					managed: true,
					ordering: [],
					indexes: [],
					customOptions: {},
				}
    		),
			new actions.CreateModel(
        		"AppConfiguration",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					app:new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"app_id","customAttributes":{},"attributeName":"app","relatedTo":"App","fieldName":"appId","onDelete":"cascade","relatedName":null,"toField":null}),
					metadata:new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"metadata_id","customAttributes":{},"attributeName":"metadata","relatedTo":"RequiredMetadataForApp","fieldName":"metadataId","onDelete":"cascade","relatedName":null,"toField":null}),
					value:new models.fields.TextField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"value","customAttributes":{},"attributeName":"value"}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "app_configuration",
					managed: true,
					ordering: [],
					indexes: [],
					customOptions: {},
				}
    		),
        ]
    }
}