export default {
    selectCreateLabel: 'Criar',
    sidebarHelloName: 'Olá, ',
    sidebarQuickSearchButtonLabel: 'Pesquisa Rápida',
    sidebarHistoryButtonLabel: 'Histórico',
    sidebarSettingsButtonLabel: 'Configurações',
    sidebarWorkspacesTitle: 'ESPAÇOS DE TRABALHO',
    workspaceEditColor: 'Cores',
    workspaceNewAreaName: 'Workspace sem nome',
    workspaceRemoveButtonLabel: 'Remover workspace',
    workspaceAddNewAppButtonLabel: 'Novo App',
    workspaceNoWorkspaceSelected: 'Nenhum workspace selecionado',
    workspaceNotUniqueErrorMessage: 'Nome do workspace deve ser único',
    formularyToolbarShareButtonLabel: 'Compartilhar',
    formularyFieldEditIsRequiredLabel: 'Obrigatório',
    formularyFieldEditLabelIsHiddenLabel: 'Ocultar titulo',
    formularyFieldEditFieldIsHiddenLabel: 'Ocultar campo',
    formularyFieldEditFieldIsUniqueLabel: 'Valor é único',
    formularyFieldEditLabelAndFieldIsHiddenMessage: 'O campo "{}" está oculto',
    formularyFieldEditRenameLabel: 'Renomear',
    formularyFieldEditDuplicateLabel: 'Duplicar',
    formularyFieldEditEditLabel: 'Editar',
    formularyFieldEditDeleteLabel: 'Excluir',
    formularyFieldNumberDefaultDecimalCharacter: ',',
    formularyFieldNumberDefaultThousandSeparatorCharacter: '.',
    formularyFieldOptionCustomHelperLabel: 'Selecione uma opção ou escreva para criar uma nova',
    formularyFieldOptionCreateOptionLabel: 'Criar',
    numberFormatTypeNumberLabel: 'Dinâmico',
    numberFormatTypeIntegerLabel: 'Inteiro',
    numberFormatTypeCurrencyLabel: 'Monetário',
    numberFormatTypePercentageLabel: 'Porcentagem'
}