export default {
    selectCreateLabel: 'Criar',
    sidebarHelloName: 'Olá, ',
    sidebarQuickSearchButtonLabel: 'Pesquisa Rápida',
    sidebarHistoryButtonLabel: 'Histórico',
    sidebarSettingsButtonLabel: 'Configurações',
    sidebarWorkspacesTitle: 'ESPAÇOS DE TRABALHO',
    workspaceEditColor: 'Cores',
    workspaceNewAreaName: 'Workspace sem nome',
    workspaceRemoveButtonLabel: 'Remover workspace',
    workspaceAddNewAppButtonLabel: 'Novo App',
    workspaceNoAppSelected: 'Nenhum app selecionado',
    workspaceNoWorkspaceSelected: 'Nenhum workspace selecionado',
    workspaceNotUniqueErrorMessage: 'Nome do workspace deve ser único',
    formularyToolbarShareButtonLabel: 'Compartilhar',
    formularyFieldEditIsRequiredLabel: 'Obrigatório',
    formularyFieldEditLabelIsHiddenLabel: 'Ocultar titulo',
    formularyFieldEditFieldIsHiddenLabel: 'Ocultar campo',
    formularyFieldEditFieldIsUniqueLabel: 'Valor é único',
    formularyFieldEditLabelAndFieldIsHiddenMessage: 'O campo "{}" está oculto',
    formularyFieldEditRenameLabel: 'Renomear',
    formularyFieldEditDuplicateLabel: 'Duplicar',
    formularyFieldEditEditLabel: 'Editar',
    formularyFieldEditDeleteLabel: 'Excluir',
    formularyFieldNumberDefaultDecimalCharacter: ',',
    formularyFieldNumberDefaultThousandSeparatorCharacter: '.',
    formularyFieldNumberDropdownMenuNumberFormatOptionLabel: 'Selecione a formatação',
    formularyFieldOptionCustomHelperLabel: 'Selecione uma opção ou escreva para criar uma nova',
    formularyFieldOptionCreateOptionLabel: 'Criar',
    formularyFieldOptionEditOptionMenuRenameButtonLabel: 'Renomear',
    formularyFieldOptionEditOptionMenuDeleteButtonLabel: 'Excluir',
    formularyFieldOptionEditOptionMenuColorLabel: 'Cores',
    formularyFieldAttachmentPlaceholder: 'Clique ou arraste os arquivos aqui',
    numberFormatTypeNumberLabel: 'Dinâmico',
    numberFormatTypeIntegerLabel: 'Inteiro',
    numberFormatTypeCurrencyLabel: 'Monetário',
    numberFormatTypePercentageLabel: 'Porcentagem',
    datePickerMonthOfTheYearJanuaryLabel: 'Janeiro',
    datePickerMonthOfTheYearFebruaryLabel: 'Fevereiro',
    datePickerMonthOfTheYearMarchLabel: 'Março',
    datePickerMonthOfTheYearAprilLabel: 'Abril',
    datePickerMonthOfTheYearMayLabel: 'Maio',
    datePickerMonthOfTheYearJuneLabel: 'Junho',
    datePickerMonthOfTheYearJulyLabel: 'Julho',
    datePickerMonthOfTheYearAugustLabel: 'Agosto',
    datePickerMonthOfTheYearSeptemberLabel: 'Setembro',
    datePickerMonthOfTheYearOctoberLabel: 'Outubro',
    datePickerMonthOfTheYearNovemberLabel: 'Novembro',
    datePickerMonthOfTheYearDecemberLabel: 'Dezembro',
    datePickerDayOfTheWeekSundayLabel: 'Domingo',
    datePickerDayOfTheWeekMondayLabel: 'Segunda',
    datePickerDayOfTheWeekTuesdayLabel: 'Terça',
    datePickerDayOfTheWeekWednesdayLabel: 'Quarta',
    datePickerDayOfTheWeekThursdayLabel: 'Quinta',
    datePickerDayOfTheWeekFridayLabel: 'Sexta',
    datePickerDayOfTheWeekSaturdayLabel: 'Sábado',
    datePickerDefaultFormat: 'DD/MM/YYYY'
}