/**
* Automatically Generated by Reflow at 2022-02-01T19:23:26.082Z
* */

'use strict'

module.exports = {
    engine: "SequelizeEngine",
    dependency: "18_auto_migration_1643677332339",
    operations: (models, actions) => {
        return [
			new actions.CreateModel(
        		"DraftType",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					name:new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"name","customAttributes":{},"attributeName":"name","maxLength":255}),
					order:new models.fields.IntegerField({"underscored":true,"primaryKey":false,"defaultValue":1,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"order","customAttributes":{},"attributeName":"order"}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "draft_type",
					managed: true,
					ordering: ["order"],
					indexes: [],
					customOptions: {},
				}
    		),
			new actions.CreateModel(
        		"Draft",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					updatedAt:new models.fields.DatetimeField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"updated_at","customAttributes":{},"attributeName":"updatedAt","autoNow":true,"autoNowAdd":false}),
					createdAt:new models.fields.DatetimeField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"created_at","customAttributes":{},"attributeName":"createdAt","autoNow":false,"autoNowAdd":true}),
					uuid:new models.fields.UUIDField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"uuid","customAttributes":{},"attributeName":"uuid","maxLength":36,"autoGenerate":false}),
					isPublic:new models.fields.BooleanField({"underscored":true,"primaryKey":false,"defaultValue":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"is_public","customAttributes":{},"attributeName":"isPublic"}),
					draftType:new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":true,"databaseName":"draft_type_id","customAttributes":{},"attributeName":"draftType","relatedTo":"DraftType","fieldName":"draftTypeId","onDelete":"cascade","relatedName":null,"toField":null}),
					bucket:new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"bucket","customAttributes":{},"attributeName":"bucket","maxLength":255}),
					fileDraftPath:new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"file_draft_path","customAttributes":{},"attributeName":"fileDraftPath","maxLength":255}),
					fileUrl:new models.fields.TextField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"file_url","customAttributes":{},"attributeName":"fileUrl"}),
					fileSize:new models.fields.BigIntegerField({"underscored":true,"primaryKey":false,"defaultValue":null,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"file_size","customAttributes":{},"attributeName":"fileSize"}),
					value:new models.fields.TextField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"value","customAttributes":{},"attributeName":"value"}),
					workspace:new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":true,"databaseName":"workspace_id","customAttributes":{},"attributeName":"workspace","relatedTo":"Workspace","fieldName":"workspaceId","onDelete":"cascade","relatedName":null,"toField":null}),
					user:new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":true,"databaseName":"user_id","customAttributes":{},"attributeName":"user","relatedTo":"User","fieldName":"userId","onDelete":"cascade","relatedName":null,"toField":null}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "draft",
					managed: true,
					ordering: ["order"],
					indexes: [],
					customOptions: {},
				}
    		),
        ]
    }
}