/**
* Automatically Generated by Reflow at 2022-02-12T23:54:54.710Z
* */

'use strict'

module.exports = {
    engine: "SequelizeEngine",
    dependency: "20_auto_migration_1644710094710",
    operations: (models, actions) => {
        return [
			new actions.ChangeColumn(
        		"Draft",
        		"fileDraftPath",
        		new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"file_draft_path","customAttributes":{},"attributeName":"fileDraftPath","maxLength":255}),
        		new models.fields.CharField({"underscored":true,"primaryKey":false,"defaultValue":"file-draft","allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"file_draft_path","customAttributes":{},"attributeName":"fileDraftPath","maxLength":255})
    		),
			new actions.ChangeColumn(
        		"Draft",
        		"bucket",
        		new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"bucket","customAttributes":{},"attributeName":"bucket","maxLength":255}),
        		new models.fields.CharField({"underscored":true,"primaryKey":false,"defaultValue":"reflow-crm","allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"bucket","customAttributes":{},"attributeName":"bucket","maxLength":255})
    		),
			new actions.ChangeModel(
        		"Draft",
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "draft",
					managed: true,
					ordering: ["order"],
					indexes: [],
					customOptions: {},
				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "draft",
					managed: true,
					ordering: [],
					indexes: [],
					customOptions: {},
				}
    		),
        ]
    }
}