/**
* Automatically Generated by Reflow at 2022-01-21T18:51:23.443Z
* */

'use strict'

module.exports = {
    engine: "SequelizeEngine",
    dependency: "15_auto_migration_1641931932705",
    operations: (models, actions) => {
        return [
			new actions.ChangeColumn(
        		"FieldDate",
        		"timeFormatType",
        		new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"time_format_type_id","customAttributes":{},"attributeName":"timeFormatType","relatedTo":"TimeFormatType","fieldName":"timeFormatTypeId","onDelete":"cascade","relatedName":null,"toField":null}),
        		new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"time_format_type_id","customAttributes":{},"attributeName":"timeFormatType","relatedTo":"TimeFormatType","fieldName":"timeFormatTypeId","onDelete":"cascade","relatedName":null,"toField":null})
    		),
			new actions.CreateColumn(
        		"Option",
        		"color",
        		new models.fields.CharField({"underscored":true,"primaryKey":false,"defaultValue":null,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"color","customAttributes":{},"attributeName":"color","maxLength":280})
    		),
        ]
    }
}