/**
* Automatically Generated by Reflow at 2022-01-09T00:09:17.291Z
* */

'use strict'

module.exports = {
    engine: "SequelizeEngine",
    dependency: "11_auto_migration_1641686769233",
    operations: (models, actions) => {
        return [
			new actions.CreateModel(
        		"SectionType",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					name:new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":true,"databaseName":"name","customAttributes":{},"attributeName":"name","maxLength":280}),
					order:new models.fields.IntegerField({"underscored":true,"primaryKey":false,"defaultValue":1,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"order","customAttributes":{},"attributeName":"order"}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "section_type",
					managed: true,
					ordering: ["order"],
					indexes: [],
					customOptions: {},
				}
    		),
			new actions.CreateModel(
        		"FieldType",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					name:new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":true,"databaseName":"name","customAttributes":{},"attributeName":"name","maxLength":280}),
					order:new models.fields.IntegerField({"underscored":true,"primaryKey":false,"defaultValue":1,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"order","customAttributes":{},"attributeName":"order"}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "field_type",
					managed: true,
					ordering: ["order"],
					indexes: [],
					customOptions: {},
				}
    		),
			new actions.CreateModel(
        		"NumberFormatType",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					name:new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":true,"databaseName":"name","customAttributes":{},"attributeName":"name","maxLength":280}),
					order:new models.fields.IntegerField({"underscored":true,"primaryKey":false,"defaultValue":1,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"order","customAttributes":{},"attributeName":"order"}),
					precision:new models.fields.BigIntegerField({"underscored":true,"primaryKey":false,"defaultValue":1,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"precision","customAttributes":{},"attributeName":"precision"}),
					prefix:new models.fields.CharField({"underscored":true,"primaryKey":false,"defaultValue":null,"allowBlank":false,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"prefix","customAttributes":{},"attributeName":"prefix","maxLength":250}),
					suffix:new models.fields.CharField({"underscored":true,"primaryKey":false,"defaultValue":null,"allowBlank":false,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"suffix","customAttributes":{},"attributeName":"suffix","maxLength":250}),
					thousandsSeparator:new models.fields.CharField({"underscored":true,"primaryKey":false,"defaultValue":null,"allowBlank":false,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"thousands_separator","customAttributes":{},"attributeName":"thousandsSeparator","maxLength":10}),
					decimalSeparator:new models.fields.CharField({"underscored":true,"primaryKey":false,"defaultValue":null,"allowBlank":false,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"decimal_separator","customAttributes":{},"attributeName":"decimalSeparator","maxLength":10}),
					base:new models.fields.BigIntegerField({"underscored":true,"primaryKey":false,"defaultValue":1,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"base","customAttributes":{},"attributeName":"base"}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "number_format_type",
					managed: true,
					ordering: ["order"],
					indexes: [],
					customOptions: {},
				}
    		),
			new actions.CreateModel(
        		"DateFormatType",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					name:new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":true,"databaseName":"name","customAttributes":{},"attributeName":"name","maxLength":280}),
					order:new models.fields.IntegerField({"underscored":true,"primaryKey":false,"defaultValue":1,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"order","customAttributes":{},"attributeName":"order"}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "date_format_type",
					managed: true,
					ordering: ["order"],
					indexes: [],
					customOptions: {},
				}
    		),
			new actions.CreateModel(
        		"TimeFormatType",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					name:new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":true,"databaseName":"name","customAttributes":{},"attributeName":"name","maxLength":280}),
					order:new models.fields.IntegerField({"underscored":true,"primaryKey":false,"defaultValue":1,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"order","customAttributes":{},"attributeName":"order"}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "time_format_type",
					managed: true,
					ordering: ["order"],
					indexes: [],
					customOptions: {},
				}
    		),
			new actions.CreateModel(
        		"Formulary",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					createdAt:new models.fields.DatetimeField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"created_at","customAttributes":{},"attributeName":"createdAt","autoNow":false,"autoNowAdd":true}),
					updatedAt:new models.fields.DatetimeField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"updated_at","customAttributes":{},"attributeName":"updatedAt","autoNow":true,"autoNowAdd":false}),
					uuid:new models.fields.UUIDField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"uuid","customAttributes":{},"attributeName":"uuid","maxLength":36,"autoGenerate":false}),
					name:new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":true,"databaseName":"name","customAttributes":{},"attributeName":"name","maxLength":280}),
					labelName:new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":true,"databaseName":"label_name","customAttributes":{},"attributeName":"labelName","maxLength":280}),
					app:new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"app_id","customAttributes":{},"attributeName":"app","relatedTo":"App","fieldName":"appId","onDelete":"cascade","relatedName":null,"toField":null}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "formulary",
					managed: true,
					ordering: [],
					indexes: [],
					customOptions: {},
				}
    		),
			new actions.CreateModel(
        		"Section",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					createdAt:new models.fields.DatetimeField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"created_at","customAttributes":{},"attributeName":"createdAt","autoNow":false,"autoNowAdd":true}),
					updatedAt:new models.fields.DatetimeField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"updated_at","customAttributes":{},"attributeName":"updatedAt","autoNow":true,"autoNowAdd":false}),
					name:new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"name","customAttributes":{},"attributeName":"name","maxLength":280}),
					labelName:new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"label_name","customAttributes":{},"attributeName":"labelName","maxLength":280}),
					order:new models.fields.IntegerField({"underscored":true,"primaryKey":false,"defaultValue":1,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"order","customAttributes":{},"attributeName":"order"}),
					formulary:new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"formulary_id","customAttributes":{},"attributeName":"formulary","relatedTo":"Formulary","fieldName":"formularyId","onDelete":"cascade","relatedName":null,"toField":null}),
					sectionType:new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"section_type_id","customAttributes":{},"attributeName":"sectionType","relatedTo":"SectionType","fieldName":"sectionTypeId","onDelete":"cascade","relatedName":null,"toField":null}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "section",
					managed: true,
					ordering: ["order"],
					indexes: [],
					customOptions: {},
				}
    		),
			new actions.CreateModel(
        		"Field",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					createdAt:new models.fields.DatetimeField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"created_at","customAttributes":{},"attributeName":"createdAt","autoNow":false,"autoNowAdd":true}),
					updatedAt:new models.fields.DatetimeField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"updated_at","customAttributes":{},"attributeName":"updatedAt","autoNow":true,"autoNowAdd":false}),
					uuid:new models.fields.UUIDField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"uuid","customAttributes":{},"attributeName":"uuid","maxLength":36,"autoGenerate":false}),
					name:new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"name","customAttributes":{},"attributeName":"name","maxLength":280}),
					labelName:new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"label_name","customAttributes":{},"attributeName":"labelName","maxLength":280}),
					placeholder:new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"placeholder","customAttributes":{},"attributeName":"placeholder","maxLength":280}),
					required:new models.fields.BooleanField({"underscored":true,"primaryKey":false,"defaultValue":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"required","customAttributes":{},"attributeName":"required"}),
					order:new models.fields.IntegerField({"underscored":true,"primaryKey":false,"defaultValue":1,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"order","customAttributes":{},"attributeName":"order"}),
					isUnique:new models.fields.BooleanField({"underscored":true,"primaryKey":false,"defaultValue":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"is_unique","customAttributes":{},"attributeName":"isUnique"}),
					fieldIsHidden:new models.fields.BooleanField({"underscored":true,"primaryKey":false,"defaultValue":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"field_is_hidden","customAttributes":{},"attributeName":"fieldIsHidden"}),
					labelIsHidden:new models.fields.BooleanField({"underscored":true,"primaryKey":false,"defaultValue":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"label_is_hidden","customAttributes":{},"attributeName":"labelIsHidden"}),
					section:new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"section_id","customAttributes":{},"attributeName":"section","relatedTo":"Section","fieldName":"sectionId","onDelete":"cascade","relatedName":null,"toField":null}),
					fieldType:new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"field_type_id","customAttributes":{},"attributeName":"fieldType","relatedTo":"FieldType","fieldName":"fieldTypeId","onDelete":"cascade","relatedName":null,"toField":null}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "field",
					managed: true,
					ordering: ["order"],
					indexes: [],
					customOptions: {},
				}
    		),
			new actions.CreateModel(
        		"FieldNumber",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					uuid:new models.fields.UUIDField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"uuid","customAttributes":{},"attributeName":"uuid","maxLength":36,"autoGenerate":false}),
					field:new models.fields.OneToOneField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":true,"dbIndex":false,"databaseName":"field_id","customAttributes":{},"attributeName":"field","relatedTo":"Field","fieldName":"fieldId","onDelete":"cascade","relatedName":null,"toField":null}),
					allowNegative:new models.fields.BooleanField({"underscored":true,"primaryKey":false,"defaultValue":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"allow_negative","customAttributes":{},"attributeName":"allowNegative"}),
					allowZero:new models.fields.BooleanField({"underscored":true,"primaryKey":false,"defaultValue":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"allow_zero","customAttributes":{},"attributeName":"allowZero"}),
					numberFormatType:new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"number_format_type_id","customAttributes":{},"attributeName":"numberFormatType","relatedTo":"NumberFormatType","fieldName":"numberFormatTypeId","onDelete":"cascade","relatedName":null,"toField":null}),
					decimalCharacter:new models.fields.CharField({"underscored":true,"primaryKey":false,"defaultValue":".","allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"decimal_character","customAttributes":{},"attributeName":"decimalCharacter","maxLength":280}),
					thousandSeparatorCharacter:new models.fields.CharField({"underscored":true,"primaryKey":false,"defaultValue":",","allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"thousand_separator_character","customAttributes":{},"attributeName":"thousandSeparatorCharacter","maxLength":280}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "field_number",
					managed: true,
					ordering: [],
					indexes: [],
					customOptions: {},
				}
    		),
			new actions.CreateModel(
        		"FieldDate",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					uuid:new models.fields.UUIDField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"uuid","customAttributes":{},"attributeName":"uuid","maxLength":36,"autoGenerate":false}),
					field:new models.fields.OneToOneField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":true,"dbIndex":false,"databaseName":"field_id","customAttributes":{},"attributeName":"field","relatedTo":"Field","fieldName":"fieldId","onDelete":"cascade","relatedName":null,"toField":null}),
					autoCreate:new models.fields.BooleanField({"underscored":true,"primaryKey":false,"defaultValue":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"auto_create","customAttributes":{},"attributeName":"autoCreate"}),
					autoUpdate:new models.fields.BooleanField({"underscored":true,"primaryKey":false,"defaultValue":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"auto_update","customAttributes":{},"attributeName":"autoUpdate"}),
					dateFormatType:new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"date_format_type_id","customAttributes":{},"attributeName":"dateFormatType","relatedTo":"DateFormatType","fieldName":"dateFormatTypeId","onDelete":"cascade","relatedName":null,"toField":null}),
					timeFormatType:new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"time_format_type_id","customAttributes":{},"attributeName":"timeFormatType","relatedTo":"TimeFormatType","fieldName":"timeFormatTypeId","onDelete":"cascade","relatedName":null,"toField":null}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "field_date",
					managed: true,
					ordering: [],
					indexes: [],
					customOptions: {},
				}
    		),
			new actions.CreateModel(
        		"FieldConnection",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					field:new models.fields.OneToOneField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":true,"dbIndex":false,"databaseName":"field_id","customAttributes":{},"attributeName":"field","relatedTo":"Field","fieldName":"fieldId","onDelete":"cascade","relatedName":null,"toField":null}),
					formulary:new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"formulary_id","customAttributes":{},"attributeName":"formulary","relatedTo":"Formulary","fieldName":"formularyId","onDelete":"cascade","relatedName":null,"toField":null}),
					fieldAsOption:new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"field_as_option_id","customAttributes":{},"attributeName":"fieldAsOption","relatedTo":"Field","fieldName":"fieldAsOptionId","onDelete":"cascade","relatedName":null,"toField":null}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "field_connection",
					managed: true,
					ordering: [],
					indexes: [],
					customOptions: {},
				}
    		),
			new actions.CreateModel(
        		"FieldOption",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					createdAt:new models.fields.DatetimeField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"created_at","customAttributes":{},"attributeName":"createdAt","autoNow":false,"autoNowAdd":true}),
					updatedAt:new models.fields.DatetimeField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"updated_at","customAttributes":{},"attributeName":"updatedAt","autoNow":true,"autoNowAdd":false}),
					uuid:new models.fields.UUIDField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"uuid","customAttributes":{},"attributeName":"uuid","maxLength":36,"autoGenerate":false}),
					field:new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"field_id","customAttributes":{},"attributeName":"field","relatedTo":"Field","fieldName":"fieldId","onDelete":"cascade","relatedName":null,"toField":null}),
					order:new models.fields.IntegerField({"underscored":true,"primaryKey":false,"defaultValue":1,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"order","customAttributes":{},"attributeName":"order"}),
					value:new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"value","customAttributes":{},"attributeName":"value","maxLength":280}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "field_option",
					managed: true,
					ordering: ["order"],
					indexes: [],
					customOptions: {},
				}
    		),
        ]
    }
}