/**
* Automatically Generated by Reflow at 2022-01-10T00:09:23.310Z
* */

'use strict'

module.exports = {
    engine: "SequelizeEngine",
    dependency: "12_auto_migration_1641686957292",
    operations: (models, actions) => {
        return [
			new actions.RemoveColumn(
        		"NumberFormatType",
        		"thousandsSeparator"
    		),
			new actions.RemoveColumn(
        		"NumberFormatType",
        		"decimalSeparator"
    		),
        ]
    }
}