/**
* Automatically Generated by Reflow at 2022-01-10T00:09:51.914Z
* */

'use strict'

module.exports = {
    engine: "SequelizeEngine",
    dependency: "13_auto_migration_1641773363310",
    operations: (models, actions) => {
        return [
			new actions.CreateColumn(
        		"NumberFormatType",
        		"thousandsSeparator",
        		new models.fields.BooleanField({"underscored":true,"primaryKey":false,"defaultValue":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"thousands_separator","customAttributes":{},"attributeName":"thousandsSeparator"})
    		),
			new actions.CreateColumn(
        		"NumberFormatType",
        		"decimalSeparator",
        		new models.fields.BooleanField({"underscored":true,"primaryKey":false,"defaultValue":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"decimal_separator","customAttributes":{},"attributeName":"decimalSeparator"})
    		),
        ]
    }
}