/**
* Automatically Generated by Reflow at 2022-02-01T01:02:12.339Z
* */

'use strict'

module.exports = {
    engine: "SequelizeEngine",
    dependency: "17_auto_migration_1643677332339",
    operations: (models, actions) => {
        return [
			new actions.CreateModel(
        		"FieldAttachment",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					uuid:new models.fields.UUIDField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"uuid","customAttributes":{},"attributeName":"uuid","maxLength":36,"autoGenerate":false}),
					field:new models.fields.OneToOneField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":true,"dbIndex":false,"databaseName":"field_id","customAttributes":{},"attributeName":"field","relatedTo":"Field","fieldName":"fieldId","onDelete":"cascade","relatedName":null,"toField":null}),
					maxNumberOfAttachments:new models.fields.IntegerField({"underscored":true,"primaryKey":false,"defaultValue":null,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"max_number_of_attachments","customAttributes":{},"attributeName":"maxNumberOfAttachments"}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "field_attachment",
					managed: true,
					ordering: [],
					indexes: [],
					customOptions: {},
				}
    		),
        ]
    }
}