/**
* Automatically Generated by Reflow at 2022-02-12T23:54:54.710Z
* */

'use strict'

module.exports = {
    engine: "SequelizeEngine",
    dependency: "22_auto_migration_1644710094710",
    operations: (models, actions) => {
        return [
			new actions.CreateModel(
        		"FieldOption",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					uuid:new models.fields.UUIDField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"uuid","customAttributes":{},"attributeName":"uuid","maxLength":36,"autoGenerate":false}),
					field:new models.fields.OneToOneField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":true,"dbIndex":false,"databaseName":"field_id","customAttributes":{},"attributeName":"field","relatedTo":"Field","fieldName":"fieldId","onDelete":"cascade","relatedName":null,"toField":null}),
					isDropdown:new models.fields.BooleanField({"underscored":true,"primaryKey":false,"defaultValue":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"is_dropdown","customAttributes":{},"attributeName":"isDropdown"}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "field_option",
					managed: true,
					ordering: [],
					indexes: [],
					customOptions: {},
				}
    		),
			new actions.CreateModel(
        		"FieldTags",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					uuid:new models.fields.UUIDField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"uuid","customAttributes":{},"attributeName":"uuid","maxLength":36,"autoGenerate":false}),
					field:new models.fields.OneToOneField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":true,"dbIndex":false,"databaseName":"field_id","customAttributes":{},"attributeName":"field","relatedTo":"Field","fieldName":"fieldId","onDelete":"cascade","relatedName":null,"toField":null}),
					isDropdown:new models.fields.BooleanField({"underscored":true,"primaryKey":false,"defaultValue":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"is_dropdown","customAttributes":{},"attributeName":"isDropdown"}),
					maxNumberOfOptions:new models.fields.IntegerField({"underscored":true,"primaryKey":false,"defaultValue":null,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"max_number_of_options","customAttributes":{},"attributeName":"maxNumberOfOptions"}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "field_tags",
					managed: true,
					ordering: [],
					indexes: [],
					customOptions: {},
				}
    		),
        ]
    }
}