/**
* Automatically Generated by Reflow at 2022-03-14T13:48:18.093Z
* */

'use strict'

module.exports = {
    engine: "SequelizeEngine",
    dependency: "23_auto_migration_1644710094710",
    operations: (models, actions) => {
        return [
			new actions.CreateModel(
        		"FieldFormulaVariable",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					uuid:new models.fields.UUIDField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"uuid","customAttributes":{},"attributeName":"uuid","maxLength":36,"autoGenerate":false}),
					fieldFormula:new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":true,"databaseName":"field_formula_id","customAttributes":{},"attributeName":"fieldFormula","relatedTo":"FieldFormula","fieldName":"fieldFormulaId","onDelete":"cascade","relatedName":null,"toField":null}),
					variable:new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":true,"databaseName":"variable_id","customAttributes":{},"attributeName":"variable","relatedTo":"Field","fieldName":"variableId","onDelete":"cascade","relatedName":null,"toField":null}),
					order:new models.fields.IntegerField({"underscored":true,"primaryKey":false,"defaultValue":0,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"order","customAttributes":{},"attributeName":"order"}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "field_formula_variable",
					managed: true,
					ordering: ["order"],
					indexes: [],
					customOptions: {},
				}
    		),
        ]
    }
}