/**
* Automatically Generated by Reflow at 2022-03-17T22:13:22.663Z
* */

'use strict'

module.exports = {
    engine: "SequelizeEngine",
    dependency: "25_auto_migration_1647485172648",
    operations: (models, actions) => {
        return [
			new actions.ChangeModel(
        		"Field",
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "field",
					managed: true,
					ordering: ["order"],
					indexes: [],
					customOptions: {},
				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "field",
					managed: true,
					ordering: [],
					indexes: [],
					customOptions: {},
				}
    		),
			new actions.RemoveColumn(
        		"Field",
        		"order"
    		),
			new actions.RemoveColumn(
        		"Field",
        		"section"
    		),
        ]
    }
}