/**
* Automatically Generated by Reflow at 2022-03-22T23:38:20.625Z
* */

'use strict'

module.exports = {
    engine: "SequelizeEngine",
    dependency: "27_auto_migration_1647984753808",
    operations: (models, actions) => {
        return [
			new actions.CreateModel(
        		"FormularyFields",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					field:new models.fields.OneToOneField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":true,"dbIndex":false,"databaseName":"field_id","customAttributes":{},"attributeName":"field","relatedTo":"Field","fieldName":"fieldId","onDelete":"cascade","relatedName":null,"toField":null}),
					order:new models.fields.IntegerField({"underscored":true,"primaryKey":false,"defaultValue":1,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"order","customAttributes":{},"attributeName":"order"}),
					formulary:new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"formulary_id","customAttributes":{},"attributeName":"formulary","relatedTo":"Formulary","fieldName":"formularyId","onDelete":"cascade","relatedName":null,"toField":null}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "formulary_fields",
					managed: true,
					ordering: ["order"],
					indexes: [],
					customOptions: {},
				}
    		),
        ]
    }
}