/**
* Automatically Generated by Reflow at 2022-03-23T03:23:45.889Z
* */

'use strict'

module.exports = {
    engine: "SequelizeEngine",
    dependency: "28_auto_migration_1647992300625",
    operations: (models, actions) => {
        return [
			new actions.CreateColumn(
        		"FieldType",
        		"hasPlaceholder",
        		new models.fields.BooleanField({"underscored":true,"primaryKey":false,"defaultValue":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"has_placeholder","customAttributes":{},"attributeName":"hasPlaceholder"})
    		),
			new actions.CreateColumn(
        		"FieldType",
        		"canBeRequired",
        		new models.fields.BooleanField({"underscored":true,"primaryKey":false,"defaultValue":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"can_be_required","customAttributes":{},"attributeName":"canBeRequired"})
    		),
			new actions.CreateColumn(
        		"FieldType",
        		"canBeUnique",
        		new models.fields.BooleanField({"underscored":true,"primaryKey":false,"defaultValue":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"can_be_unique","customAttributes":{},"attributeName":"canBeUnique"})
    		),
			new actions.CreateColumn(
        		"FieldType",
        		"canFieldBeHidden",
        		new models.fields.BooleanField({"underscored":true,"primaryKey":false,"defaultValue":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"can_field_be_hidden","customAttributes":{},"attributeName":"canFieldBeHidden"})
    		),
			new actions.CreateColumn(
        		"FieldType",
        		"canlabelBeHidden",
        		new models.fields.BooleanField({"underscored":true,"primaryKey":false,"defaultValue":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"canlabel_be_hidden","customAttributes":{},"attributeName":"canlabelBeHidden"})
    		),
			new actions.CreateColumn(
        		"FieldType",
        		"hasValues",
        		new models.fields.BooleanField({"underscored":true,"primaryKey":false,"defaultValue":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"has_values","customAttributes":{},"attributeName":"hasValues"})
    		),
			new actions.CreateModel(
        		"FieldLabel",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					name:new models.fields.TextField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":true,"databaseName":"name","customAttributes":{},"attributeName":"name"}),
					labelImageBucket:new models.fields.CharField({"underscored":true,"primaryKey":false,"defaultValue":"reflow-crm","allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"label_image_bucket","customAttributes":{},"attributeName":"labelImageBucket","maxLength":200}),
					labelImagePath:new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"label_image_path","customAttributes":{},"attributeName":"labelImagePath","maxLength":250}),
					labelImageUrl:new models.fields.TextField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"label_image_url","customAttributes":{},"attributeName":"labelImageUrl"}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "field_label",
					managed: true,
					ordering: [],
					indexes: [],
					customOptions: {},
				}
    		),
			new actions.CreateColumn(
        		"Field",
        		"label",
        		new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"label_id","customAttributes":{},"attributeName":"label","relatedTo":"FieldLabel","fieldName":"labelId","onDelete":"cascade","relatedName":null,"toField":null})
    		),
        ]
    }
}