/**
* Automatically Generated by Reflow at 2022-03-24T00:11:15.557Z
* */

'use strict'

module.exports = {
    engine: "SequelizeEngine",
    dependency: "29_auto_migration_1648005825889",
    operations: (models, actions) => {
        return [
			new actions.CreateModel(
        		"FieldTypeCategoryType",
        		{ 
					id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					name:new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"name","customAttributes":{},"attributeName":"name","maxLength":280}),
					order:new models.fields.IntegerField({"underscored":true,"primaryKey":false,"defaultValue":1,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"order","customAttributes":{},"attributeName":"order"}),
 				},
        		{
					autoId: true,
					primaryKeyField: new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{},"attributeName":"id"}),
					abstract: false,
					underscored: true,
					tableName: "field_type_category",
					managed: true,
					ordering: [],
					indexes: [],
					customOptions: {},
				}
    		),
			new actions.CreateColumn(
        		"FieldType",
        		"category",
        		new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":true,"unique":false,"dbIndex":false,"databaseName":"category_id","customAttributes":{},"attributeName":"category","relatedTo":"FieldTypeCategoryType","fieldName":"categoryId","onDelete":"cascade","relatedName":null,"toField":null})
    		),
        ]
    }
}