/**
* Automatically Generated by Reflow at 2022-03-24T00:13:38.516Z
* */

'use strict'

module.exports = {
    engine: "SequelizeEngine",
    dependency: "30_auto_migration_1648080675558",
    operations: (models, actions) => {
        return [
			new actions.ChangeColumn(
        		"FieldLabel",
        		"labelImagePath",
        		new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"label_image_path","customAttributes":{},"attributeName":"labelImagePath","maxLength":250}),
        		new models.fields.CharField({"underscored":true,"primaryKey":false,"defaultValue":"field-label-image","allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"label_image_path","customAttributes":{},"attributeName":"labelImagePath","maxLength":250})
    		),
        ]
    }
}