/**
* Automatically Generated by Reflow at 2022-03-24T00:20:04.409Z
* */

'use strict'

module.exports = {
    engine: "SequelizeEngine",
    dependency: "31_auto_migration_1648080818517",
    operations: (models, actions) => {
        return [
			new actions.RenameColumn(
        		"FieldType",
        		"canLabelBeHidden",
        		"canlabelBeHidden",
        		new models.fields.BooleanField({"underscored":true,"primaryKey":false,"defaultValue":true,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"can_label_be_hidden","customAttributes":{},"attributeName":"canLabelBeHidden"})
    		),
        ]
    }
}