/**
* Automatically Generated by Reflow at 2022-04-09T12:12:02.134Z
* */

'use strict'

module.exports = {
    engine: "SequelizeEngine",
    dependency: "32_auto_migration_1648081204410",
    operations: (models, actions) => {
        return [
			new actions.RenameColumn(
        		"FieldConnection",
        		"app",
        		"formulary",
        		new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"app_id","customAttributes":{},"attributeName":"app","relatedTo":"App","fieldName":"appId","onDelete":"cascade","relatedName":null,"toField":null})
    		),
			new actions.ChangeColumn(
        		"FieldConnection",
        		"app",
        		new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"formulary_id","customAttributes":{},"attributeName":"formulary","relatedTo":"Formulary","fieldName":"formularyId","onDelete":"cascade","relatedName":null,"toField":null}),
        		new models.fields.ForeignKeyField({"underscored":true,"primaryKey":false,"allowBlank":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"app_id","customAttributes":{},"attributeName":"app","relatedTo":"App","fieldName":"appId","onDelete":"cascade","relatedName":null,"toField":null})
    		),
        ]
    }
}